"""
Alert model - output from the detection engine.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict


class Severity(str, Enum):
    """Alert severity levels aligned with SOC standards."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(BaseModel):
    """
    Security alert generated by a detection rule.
    
    Contains structured evidence that will be passed to the LLM
    for reasoning and recommendations.
    """
    
    rule_id: str = Field(
        description="Unique identifier for the detection rule"
    )
    rule_name: str = Field(
        description="Human-readable rule name"
    )
    description: str = Field(
        description="Brief description of what was detected"
    )
    severity: Severity = Field(
        description="Alert severity level"
    )
    mitre_tactics: List[str] = Field(
        default_factory=list,
        description="Relevant MITRE ATT&CK tactic IDs"
    )
    mitre_techniques: List[str] = Field(
        default_factory=list,
        description="Relevant MITRE ATT&CK technique IDs"
    )
    evidence: dict = Field(
        description="Structured evidence (counts, IPs, timestamps, etc.)"
    )
    triggered_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When the alert was generated"
    )
    source_ips: List[str] = Field(
        default_factory=list,
        description="Source IPs involved in the alert"
    )
    affected_users: List[str] = Field(
        default_factory=list,
        description="Users affected or targeted"
    )
    log_entry_count: int = Field(
        default=0,
        description="Number of log entries that contributed to this alert"
    )
    time_window: Optional[str] = Field(
        default=None,
        description="Time window of the detected activity"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "rule_id": "BRUTE_FORCE_001",
                "rule_name": "SSH Brute Force Attack",
                "description": "Multiple failed SSH login attempts detected from single IP",
                "severity": "high",
                "mitre_tactics": ["TA0006"],
                "mitre_techniques": ["T1110.001"],
                "evidence": {
                    "failed_attempts": 47,
                    "time_window_minutes": 5,
                    "targeted_accounts": ["admin", "root", "ubuntu"]
                },
                "triggered_at": "2024-01-15T03:27:42Z",
                "source_ips": ["192.168.1.100"],
                "affected_users": ["admin", "root", "ubuntu"],
                "log_entry_count": 47,
                "time_window": "03:22:15 - 03:27:42 UTC"
            }
        }
    )
